### ISSUE TITLE
Duplicate user names

### ISSUE THREAD

**Issue by mosee101** [ddan9/webchat#4]
Is there a way to prevent users from duplicating any name that sends a message? 

![webchat1](https://user-images.githubusercontent.com/61285062/189552394-06c78b14-31a4-497e-ad00-acf934ae009d.png)

It doesn't really makes sense that I can be typing as one username and someone uses that same screen name and types as my name.

Also messages can sometimes appear on the left or right of the screen, is this intended?

And lastly you can use emoticon smiles as the usernames, is this also intended? (tested on mobile android)

**Comment by ddan9** [comment]
Hi, Mo! 

Thank you for using and testing the webchat) I will try to answer your questions 

Because the chat architecture does not initially provide for registration and is aimed at anonymity and peer-to-peer, nickname duplication is a side effect of this approach 

Webchat has the ability to work with basic authentication through a web server, which can help you solve this problem. To do this, you need to configure the web server and the chat itself 

In addition, you can view information about the sender and the message by hovering over the nickname. This will help control the situation 

In addition, you can check the script sources (specifically functions/presets.php) and find out all the features of the chat at the moment. Perhaps you decide to change something there 

Regarding the location of messages. The chat is designed so that the client receives its key from the server to identify messages based on the address. It should show messages written by you personally on the right, and other people on the left. If so, then everything is correct. At least during my personal use, I did not notice any bugs regarding this 

Messages are encoded in UTF-8. It's not that I'm considering the use of emoticons in principle, but why not? You can only ask people not to use them in nicknames or take everything under tight control with the basic authentication 

By the way, the mobile version is not available at the moment. It will appear only after the full completion of the desktop version 

In the end, I can not say that at the moment the chat is designed for a large audience. Rather, for private use between people who know each other well. It definitely needs improvement 

If you want to help in development, I will be glad to any help. If you have any additional questions, write to me

Hope I could be of some help to you. Enjoy using)

12.09.2022, 01:56, Mo < ***@***.*** ***@***.*** >
Is there a way to prevent users from duplicating any name that sends a message?
https://user-images.githubusercontent.com/61285062/189552394-06c78b14-31a4-497e-ad00-acf934ae009d.png webchat1
It doesn't really makes sense that I can be typing as one username and someone uses that same screen name and types as my name.
Also messages can sometimes appear on the left or right of the screen, is this intended?
And lastly you can use emoticon smiles as the usernames, is this also intended? (tested on mobile android)

**Comment by mosee101** [comment]
I recently registered a domain to commence building a chat site. This script is very good. But like you stated its not designed for large amounts of users (which I need). If this changes I would consider using this code. It is very good I find. Unfortunately I might have problems trying to configure or modify it to my liking as I am not as advanced as you. Right now I am testing it local If I have anymore questions I will contact you. And if you can get this code to support a large amount of users that would help. 

As for the mobile version, I got it to render on my phone screen to normal mobile standards by changing code in the html header tags in template directory.

Thanks
